%define name		vcftools
%define release		1
%define version 	0.1.16
%define installroot 	/opt/bio/%{name}
%define buildroot       %{_topdir}/%{name}-%{version}-root
%define _prefix		%{installroot}

BuildRoot:	%{buildroot}
Summary:	vcftools
Name: 		%{name}
Version: 	%{version}
Release: 	%{release}
Source: 	%{name}-v%{version}.tar.gz
Patch0:		perl-lib-path.patch
Prefix: 	%{installroot}
Group: 		Development/Tools
License:        LGPL-3|https://github.com/vcftools/vcftools/blob/master/LICENSE
AutoReq:	yes

%global __requires_exclude ^perl
%global __provides_exclude ^perl

Requires:	opt-perl(Carp)
Requires:	opt-perl(Data::Dumper)
Requires:	opt-perl(Exporter)
Requires:	opt-perl(FindBin)
Requires:	opt-perl(IO::Select)
Requires:	opt-perl(IPC::Open2)
Requires:	opt-perl(IPC::Open3)
Requires:	opt-perl(List::Util)
Requires:	opt-perl(POSIX)
Requires:	opt-perl(base)
Requires:	opt-perl(lib)
Requires:	opt-perl(strict)
Requires:	opt-perl(vars)
Requires:	opt-perl(warnings)

%description
Welcome to VCFtools - a program package designed for working with VCF files,
such as those generated by the 1000 Genomes Project. The aim of VCFtools is to
provide methods for working with VCF files: validating, merging, comparing and
calculate some basic population genetic statistics. 


%prep
%setup -q -n %{name}-%{version} 
%patch0 -p 1

%build
./autogen.sh
./configure --prefix=%{_prefix} --with-pmdir=lib
make -j `nproc`

%install
make install DESTDIR=%{buildroot} 

%files
%defattr(644,root,root,755)
%doc LICENSE
%doc README.md
%defattr(-,root,root)
%dir %{_prefix}
%{_prefix}/lib
%{_datadir}
%defattr(0755,root,root,0755)
%{_bindir}
