# This is a  spec file for transdecoder
# requires installing openmpi.x86_64, openmpi-devel.x86_64
# openmpi provides mpicc compiler, therefore its dir must
# be added to $PATH
# requires perl module ImageMagick-perl.x86_64, which is 
# available on centos repo and which has the following dependencies:
# ImageMagick.x86_64, OpenEXR-libs, ilmbase, libwmf-lite
# In order for the MPI to work, the following path:
# /opt/bio/transdecoder-16/util/lib64 must be add to $LD_LIBRARY_PATH variable

%define name		TransDecoder
%define version 	5.5.0
%define release		1
%define buildroot       %{_topdir}/%{name}-%{version}-root
%define installroot     /opt/bio/%{name}
%define _prefix         %{installroot}


BuildRoot:	%{buildroot}
Summary: 	TransDecoder identifies candidate coding regions within transcript sequences.
Name: 		%{name}
Version: 	%{version}
Release: 	%{release}
Source: 	%{name}-v%{version}.tar.gz
Packager:	Timothy Forbes <timothy.forbes@canada.ca>
URL:            https://github.com/TransDecoder/TransDecoder
Prefix: 	%{_prefix}
Group: 		BioInformatics/Tools
License:        Copyright (c) 2012, The Broad Institute, Inc. All rights reserved.	
AutoReq:	yes

Patch0:         env-perl.patch

%global         __requires_exclude ^perl
%global         __provides_exclude ^perl
Provides:	opt-perl(CDS_exon_obj)
Provides:	opt-perl(Command)
Provides:	opt-perl(CoordSet_node)
Provides:	opt-perl(DelimParser)
Provides:	opt-perl(DelimParser::Reader)
Provides:	opt-perl(DelimParser::Writer)
Provides:	opt-perl(Fasta_reader)
Provides:	opt-perl(Fasta_retriever)
Provides:	opt-perl(GFF3_utils2)
Provides:	opt-perl(GTF)
Provides:	opt-perl(GTF::Feature)
Provides:	opt-perl(GTF::Gene)
Provides:	opt-perl(GTF::Transcript)
Provides:	opt-perl(GTF_utils2)
Provides:	opt-perl(Gene_obj)
Provides:	opt-perl(Longest_orf)
Provides:	opt-perl(Nuc_translator)
Provides:	opt-perl(Overlap_piler)
Provides:	opt-perl(PWM)
Provides:	opt-perl(Pipeliner)
Provides:	opt-perl(Process_cmd)
Provides:	opt-perl(Sequence)
Provides:	opt-perl(mRNA_exon_obj)

%description
TransDecoder identifies candidate coding regions within transcript sequences,
such as those generated by de novo RNA-Seq transcript assembly using Trinity, or
constructed based on RNA-Seq alignments to the genome using Tophat and
Cufflinks.
TransDecoder identifies likely coding sequences based on the following criteria:
- a minimum length open reading frame (ORF) is found in a transcript sequence
- a log-likelihood score similar to what is computed by the GeneID software is >
  0.
- the above coding score is greatest when the ORF is scored in the 1st reading
  frame as compared to scores in the other 5 reading frames.
- if a candidate ORF is found fully encapsulated by the coordinates of another
  candidate ORF, the longer one is reported. However, a single transcript can
  report multiple ORFs (allowing for operons, chimeras, etc).
- optional the putative peptide has a match to a Pfam domain above the noise
  cutoff score.
The software is primarily maintained by Brian Haas at the Broad Institute and
Alexie Papanicolaou at the Commonwealth Scientific and Industrial Research
Organisation (CSIRO). It is integrated into other related software such as
Trinity, PASA, EVidenceModeler, and Trinotate.

%prep
%setup -qn %{name}-%{name}-v%{version}
%patch0 -p 1

%build

%install
mkdir -p %{buildroot}%{installroot}
rm -fr TransDecoder.wiki/ __testing/ sample_data/ util/bin/ util/PWM/__deprecated/ util/__pwm_tests/ util/misc/ TransDecoder.lrgTests/ Makefile
cp -r * %{buildroot}%{installroot}


# (tf) Confirmed that the following links do not exist on the old Biocluster, so not including them 
#      for rebuild
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm %{buildroot}%{installroot}/pfam/
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin %{buildroot}%{installroot}/pfam/
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3f %{buildroot}%{installroot}/pfam/
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3i %{buildroot}%{installroot}/pfam/
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3m %{buildroot}%{installroot}/pfam/
#ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3p %{buildroot}%{installroot}/pfam/


%files
%defattr(755,root,root,755)
%{_prefix}/util
#%{installroot}
#%{_prefix}
%defattr(644,root,root,755)
%doc LICENSE.txt
%doc Changelog.txt
%doc notes
%doc README.md
%{_prefix}/PerlLib/
%attr(755, root, root) /opt/bio/%{name}/TransDecoder.LongOrfs
%attr(755, root, root) /opt/bio/%{name}/TransDecoder.Predict
%attr(644, root, root) /opt/bio/%{name}/Changelog.txt
%attr(644, root, root) /opt/bio/%{name}/LICENSE.txt
%attr(644, root, root) /opt/bio/%{name}/notes
%attr(644, root, root) /opt/bio/%{name}/README.md
%attr(644, root, root) /opt/bio/%{name}/util/PWM/README.md

