# This is a  spec file for transdecoder
# requires installing openmpi.x86_64, openmpi-devel.x86_64
# openmpi provides mpicc compiler, therefore its dir must
# be added to $PATH
# requires perl module ImageMagick-perl.x86_64, which is 
# available on centos repo and which has the following dependencies:
# ImageMagick.x86_64, OpenEXR-libs, ilmbase, libwmf-lite
# In order for the MPI to work, the following path:
# /opt/bio/transdecoder-16/util/lib64 must be add to $LD_LIBRARY_PATH variable

### define _topdir	 	/home/rpmbuild/rpms/transdecoder
%define name		transdecoder
%define release		1
%define version 	16
%define installroot 	/opt/bio/%{name}

BuildRoot:	%{buildroot}
Summary: 	TransDecoder identifies candidate coding regions within transcript sequences.
Name: 		%{name}
Version: 	%{version}
Release: 	%{release}
Source: 	%{name}_rel16JAN2014.tar.bz2
Patch0:         %{name}-%{version}-%{release}.PerlLib.patch0
Patch1:	        %{name}-%{version}-%{release}.makefile.patch1
Patch2:         %{name}-%{version}-%{release}.util.bin.patch2
Packager:	Zaky Adam <zaky.adam@grc.gc.ca>
URL:            http://transdecoder.sourceforge.net/
Prefix: 	/opt/bio
Group: 		Development/Tools
License:        BSD|Verified by emailing creator (transdecoder-users@lists.sf.net)	
AutoReq:	yes

%description
TransDecoder identifies candidate coding regions within transcript sequences,
such as those generated by de novo RNA-Seq transcript assembly using Trinity, or
constructed based on RNA-Seq alignments to the genome using Tophat and
Cufflinks.
TransDecoder identifies likely coding sequences based on the following criteria:
- a minimum length open reading frame (ORF) is found in a transcript sequence
- a log-likelihood score similar to what is computed by the GeneID software is >
  0.
- the above coding score is greatest when the ORF is scored in the 1st reading
  frame as compared to scores in the other 5 reading frames.
- if a candidate ORF is found fully encapsulated by the coordinates of another
  candidate ORF, the longer one is reported. However, a single transcript can
  report multiple ORFs (allowing for operons, chimeras, etc).
- optional the putative peptide has a match to a Pfam domain above the noise
  cutoff score.
The software is primarily maintained by Brian Haas at the Broad Institute and
Alexie Papanicolaou at the Commonwealth Scientific and Industrial Research
Organisation (CSIRO). It is integrated into other related software such as
Trinity, PASA, EVidenceModeler, and Trinotate.

%prep
%setup -q -n transdecoder_rel16JAN2014
%patch -P 0 -p1
%patch -P 1 -p1
%patch -P 2 -p1

%build
make nopfam_nocdhit

%install
mkdir -p %{buildroot}%{installroot}
cp cdna_alignment_orf_to_genome_orf.pl pfam_runner.pl TransDecoder %{buildroot}%{installroot}
cp -r PerlLib %{buildroot}%{installroot}
cp -r pfam %{buildroot}%{installroot}
cp -r util %{buildroot}%{installroot}
rm -r %{buildroot}%{installroot}/util/lib 
rm -r %{buildroot}%{installroot}/util/include

ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm %{buildroot}%{installroot}/pfam/
ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin %{buildroot}%{installroot}/pfam/
ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3f %{buildroot}%{installroot}/pfam/
ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3i %{buildroot}%{installroot}/pfam/
ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3m %{buildroot}%{installroot}/pfam/
ln -s /isilon/biodiversity/pipelines/transdecoder/pfam/v27.0/Pfam-AB.hmm.bin.h3p %{buildroot}%{installroot}/pfam/


%files
%defattr(755,root,root,755)
%{installroot}
%defattr(644,root,root,755)
%{installroot}/PerlLib/Fasta_reader.pm
%{installroot}/PerlLib/Gene_obj_indexer.pm
%{installroot}/PerlLib/Gene_obj.pm
%{installroot}/PerlLib/GFF3_utils.pm
%{installroot}/PerlLib/Longest_orf.pm
%{installroot}/PerlLib/Nuc_translator.pm
%{installroot}/PerlLib/TiedHash.pm
%{installroot}/util/lib64/libffindex.a
%{installroot}/util/lib64/libffindex.so
%{installroot}/util/lib64/libffindex.so.0.1
