### %define _topdir           /home/rpmbuild/work/MBB-Bio-Roll/mbb-bio/bcl2fastq
%define name 		bcl2fastq2
%define version 	2.20.0.422
%define release 	1
%define installroot	/opt/bio/%{name}

Name:		%{name}
Version:	%{version}
Release: 	%{release}
Source0:	ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-tar.zip
Prefix:		%{installroot}
Summary: 	Illumina utility to convert BCL files to the FASTQ format.
Group:		Bioinformatics/Tools
License: 	Illumina EULA
Vendor: 	Illumina, Inc.
Packager: 	Iyad Kandalaft <iyad.kandalaft@agr.gc.ca>
Url: 		http://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html
AutoReq: 	yes
AutoProv: 	no
Provides: 	bcl2fastq2 = %{version}

%description
bcl2fastq Conversion Software both demultiplexes data and converts BCL files generated by Illumina sequencing systems to standard FASTQ file formats for downstream analysis.

%prep
%setup -q -c
tar xvf *.tar.gz
cd bcl2fastq
chmod +x src/configure

%build
cd bcl2fastq/src
./configure --prefix=%{installroot} --force-builddir --with-cmake=`which cmake`
make -j `nproc`

%install
cd bcl2fastq/src
make install DESTDIR=%{buildroot}

%files 
%defattr(644,root,root,755)
%dir %{installroot}
%{installroot}/share
%defattr(755,root,root,755)
%dir %{installroot}/bin
%{installroot}/bin/bcl2fastq
