# This is a  spec file for maq

### define _topdir	 	/home/rpmbuild/rpms/maq
%define name		maq
%define release		1
%define version 	0.7.1
%define installroot 	/opt/bio/%{name}

BuildRoot:	%{buildroot}
Summary: 	Maq stands for Mapping and Assembly with Quality. It builds assembly by mapping short reads to reference sequences. It also simulates reads.
Name: 		%{name}
Version: 	%{version}
Release: 	%{release}
Source: 	%{name}-%{version}.tar.bz2
Patch0:         %{name}-%{version}-%{release}.patch0
Patch1:         %{name}-%{version}-%{release}.patch1
Patch2:         %{name}-%{version}-%{release}.patch2
Patch3:         %{name}-%{version}-%{release}.patch3
Packager:	Zaky Adam <zaky.adam@grc.gc.ca>
URL:            http://maq.sourceforge.net/
Prefix: 	/opt/bio
Group: 		Development/Tools
License:        GNUv2
AutoReq:	yes

%description
Maq is a software that builds mapping assemblies from short reads generated by
the next-generation sequencing machines. It is particularly designed for
Illumina-Solexa 1G Genetic Analyzer, and has preliminary functions to handle ABI
SOLiD data. 
Maq first aligns reads to reference sequences and then calls the consensus. At
the mapping stage, maq performs ungapped alignment. For single-end reads, maq is
able to find all hits with up to 2 or 3 mismatches, depending on a command-line
option; for paired-end reads, it always finds all paired hits with one of the
two reads containing up to 1 mismatch. At the assembling stage, maq calls the
consensus based on a statistical model. It calls the base which maximizes the
posterior probability and calculates a phred quality at each position along the
consensus. Heterozygotes are also called in this process.

%prep
%setup -q
%patch -P 0 -p1
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1

%build
mkdir -p %{buildroot}%{installroot}
./configure --prefix=%{buildroot}%{installroot}
make

%install
#mkdir -p %{buildroot}%{installroot}
make install

%files
%defattr(755,root,root)
%{installroot}
